[project]
name = "django-file-image-uploads-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django-extensions>=3.2.3",
    "django>=5.1.3",
    "django-rest-framework>=0.1.0",
    "pillow>=11.0.0",
]
